## valid uuid = 8f4b7b9c-3f7a-4b6c-8b0c-1c9c5b8b9b6a

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "User1",
    "email": "user_email.com",
    "password": "123"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/390761fa-0546-4db0-9214-0444d6f31d6e

###
PATCH  http://localhost:3000/users/390761fa-0546-4db0-9214-0444d6f31d6e
Content-Type: application/json

{
    "name": "User2",
    "email": "user2_email.com",
    "password": "1234"
}

###
DELETE  http://localhost:3000/users/f47a1c39-c497-4287-9b75-496c6be71f1c


## valid uuid = 8f4b7b9c-3f7a-4b6c-8b0c-1c9c5b8b9b6a

### 
POST http://localhost:3000/wallets
Content-Type: application/json

{
    "user_id": "0f521fd0-c180-4c22-8fe0-68702223917a"
}

###
GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/07ff7f9c-5eef-45b6-a4bd-ebb45243b3ed

###
PATCH  http://localhost:3000/wallets/390761fa-0546-4db0-9214-0444d6f31d6e
Content-Type: application/json

{
    "name": "User2",
    "email": "user2_email.com",
    "password": "1234"
}

###
DELETE  http://localhost:3000/wallets/f47a1c39-c497-4287-9b75-496c6be71f1c

### 
GET  http://localhost:3000/categories

### 
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Lazer"
}

### 
POST http://localhost:3000/goals
Content-Type: application/json

{
    "name": "Comprar Carro",
    "description": "Comprar um carrito até o fim do ano",
    "balance": 150,
    "end_date": "2024-12-31"
}

###
POST http://localhost:3000/transactions
Content-Type: application/json

{
    "wallet_id": "f4092263-4b3e-4dfd-b1a5-f2c6d9c25f14",
  "category_id": "87a057fc-abbc-482f-94a6-edadfc8c18a8",
  "value": 100,
  "name": "lanche fim de semana",
  "status": "Pendente",
  "type": "DESPESA",
  "effective_date": "2024-02-10"
}